'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useAuth} from '@/context/AuthContext';
import {isUuid} from '@/lib/operations/pilot-validation';
import {pilotScopeAction} from '../gunluk/actions';
import {rosterListAction,rosterHistoryAction} from './actions';
import type {CommandScope} from '@/lib/operations/pending-commands';
import type {FixedRosterRecord,RosterHistoryEntry} from '@/lib/operations/fixed-roster';
import RosterEditor from './RosterEditor';
type Page=Extract<Awaited<ReturnType<typeof rosterListAction>>,{ok:true}>['data'];
export type RosterRow=FixedRosterRecord&{workerName:string;workerActive:boolean};
export default function Roster(){
 const search=useSearchParams(),{user,role,loading}=useAuth();
 return <Content key={`${user?.id}:${search.get('firma')}:${search.get('sube')}`} actorId={user?.id??''} allowed={role==='operasyon'||role==='yonetici'} loading={loading} companyId={search.get('firma')??''} locationId={search.get('sube')??''}/>;
}
function Content({actorId,allowed,loading,companyId,locationId}:{actorId:string;allowed:boolean;loading:boolean;companyId:string;locationId:string}){
 const [scope,setScope]=useState<CommandScope|null>(null),[day,setDay]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date())),[history,setHistory]=useState(false),[offset,setOffset]=useState(0);
 const [data,setData]=useState<Page|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [editor,setEditor]=useState<{mode:'save'|'cancel'|'idp';row:RosterRow|null}|null>(null),[audit,setAudit]=useState<RosterRow|null>(null);
 const [recover,setRecover]=useState(false),seq=useRef(0);
 useEffect(()=>{let current=true;if(loading||!allowed)return;pilotScopeAction().then(r=>{if(!current)return;if(r.ok&&r.data.actorId===actorId)setScope(r.data);else setError('Çalışma şirketi doğrulanamadı. Sayfayı yenileyin.');}).catch(()=>{if(current)setError('Oturum alınamadı. Sayfayı yenileyin.');});return()=>{current=false;};},[actorId,allowed,loading]);
 const storageKey=scope?`bps:roster:v1:${scope.actorId}:${scope.tenantId}:${companyId}:${locationId}`:'';
 useEffect(()=>{if(!storageKey)return;try{setRecover(!!sessionStorage.getItem(storageKey));}catch{setError('İşlem kurtarma alanı açılamadı. Tarayıcı depolamasını kontrol edin.');}},[storageKey]);
 const load=useCallback(async()=>{const ticket=++seq.current;setAudit(null);setData(null);if(!scope||!isUuid(companyId)||!isUuid(locationId))return;setBusy(true);setError('');try{const r=await rosterListAction(scope,{companyId,locationId,day,offset,history});if(ticket!==seq.current)return;if(r.ok)setData(r.data);else setError(r.message);}catch{if(ticket===seq.current)setError('Kadro alınamadı. Yeniden deneyin.');}finally{if(ticket===seq.current)setBusy(false);}},[scope,companyId,locationId,day,offset,history]);
 useEffect(()=>{void load();return()=>{seq.current++;};},[load]);
 if(loading)return <p role="status">Oturum yükleniyor…</p>;
 if(!allowed)return <p>Şube kadrosuna erişiminiz yok.</p>;
 if(!isUuid(companyId)||!isUuid(locationId))return <section><h1 className="text-xl font-semibold">Şube kadrosu</h1><p className="my-3">Önce şube listesinden bir şube seçin.</p><Link className="underline" href="/talepler/dizin">Şube listesini aç</Link></section>;
 return <section className="mx-auto max-w-5xl space-y-5"><Link className="inline-flex min-h-11 items-center underline" href={`/talepler/dizin?firma=${companyId}`}>← Şubelere dön</Link><header><h1 className="text-2xl font-semibold">Şube kadrosu</h1>{data&&<p className="mt-2 text-slate-600">{data.companyName} · {data.locationName}</p>}<p className="mt-2 text-sm text-slate-600">Şubede görevli sabit personeli yönetin; izne çıkan personelin yerine İDP talebi açın.</p></header>
 {notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3">{notice}</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3">{error}</p>}
 {recover&&!editor&&<div className="rounded-xl border border-amber-300 p-4"><p>Önceki işlemin sonucu henüz kontrol edilmedi.</p><button className="mt-2 min-h-11 underline" onClick={()=>setEditor({mode:'save',row:null})}>İşlemi aç ve sonucunu kontrol et</button></div>}
 {editor&&scope?<RosterEditor scope={scope} companyId={companyId} locationId={locationId} storageKey={storageKey} mode={editor.mode} row={editor.row} day={day} onClose={()=>{setEditor(null);try{setRecover(!!sessionStorage.getItem(storageKey));}catch{setRecover(true);}void load();}} onSaved={message=>{setAudit(null);setNotice(message);setRecover(false);setEditor(null);void load();}}/>:<>
 <div className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Kadro tarihi<input type="date" value={day} min="2000-01-01" max="2100-12-31" disabled={history} onChange={e=>{setDay(e.target.value);setOffset(0);}} className="mt-1 block min-h-11 rounded-lg border p-2"/></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={history} onChange={e=>{setHistory(e.target.checked);setOffset(0);}}/>Geçmiş ve iptal kayıtları dahil</label><button className="min-h-11 rounded-lg border px-4" disabled={busy} onClick={()=>void load()}>Yenile</button><button className="min-h-11 rounded-lg bg-blue-700 px-4 text-white disabled:opacity-40" disabled={!scope||!data||recover} onClick={()=>{setNotice('');setEditor({mode:'save',row:null});}}>Kadroya personel ekle</button></div>
 {busy?<p role="status">Kadro yükleniyor…</p>:data&&<><ul className="grid gap-3 md:grid-cols-2">{data.rows.map(row=><li key={row.id} className="rounded-xl border bg-white p-4"><h2 className="font-semibold">{row.workerName}</h2><p className="mt-1 text-sm">{row.position} · {row.service_line}</p><p className="mt-1 text-sm text-slate-600">{row.starts_on} → {row.ends_on??'Devam ediyor'}{row.cancelled?' · İptal edildi':''}{!row.workerActive?' · Personel pasif':''}</p><div className="mt-3 flex flex-wrap gap-2">{!row.cancelled&&<><button disabled={recover} className="min-h-11 rounded-lg border px-3 disabled:opacity-40" onClick={()=>setEditor({mode:'save',row})}>Düzenle / bitir</button><button disabled={recover||!row.workerActive} className="min-h-11 rounded-lg bg-blue-50 px-3 text-blue-800 disabled:opacity-40" onClick={()=>setEditor({mode:'idp',row})}>İzin / İDP talebi aç</button><button disabled={recover} className="min-h-11 px-3 text-red-700 disabled:opacity-40" onClick={()=>setEditor({mode:'cancel',row})}>Kaydı iptal et</button></>}<button className="min-h-11 px-3 underline" onClick={()=>setAudit(row)}>Geçmiş</button></div></li>)}</ul>{!data.rows.length&&<p className="rounded-xl border p-5">{history?'Bu şubede kadro kaydı yok.':'Seçilen tarihte kadro kaydı yok. Personel ekleyin veya tarihi değiştirin.'}</p>}<div className="flex gap-4"><button disabled={!offset} className="min-h-11 underline disabled:opacity-40" onClick={()=>setOffset(n=>Math.max(0,n-50))}>Önceki</button><button disabled={!data.hasMore||offset>=100000} className="min-h-11 underline disabled:opacity-40" onClick={()=>setOffset(n=>n+50)}>Sonraki</button></div></>}
 </>}{audit&&scope&&<History key={audit.id} scope={scope} row={audit} onClose={()=>setAudit(null)}/>}</section>;
}
function History({scope,row,onClose}:{scope:CommandScope;row:RosterRow;onClose:()=>void}){
 const [offset,setOffset]=useState(0),[data,setData]=useState<{rows:RosterHistoryEntry[];hasMore:boolean}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let current=true;setData(null);setError('');rosterHistoryAction(scope,row.id,offset).then(r=>{if(!current)return;if(r.ok)setData(r.data);else setError(r.message);}).catch(()=>{if(current)setError('Geçmiş alınamadı.');});return()=>{current=false;};},[scope,row.id,offset]);
 return <section className="space-y-3 rounded-xl border bg-slate-50 p-4" aria-label="Kadro geçmişi"><div className="flex justify-between gap-3"><h2 className="font-semibold">{row.workerName} · Kayıt geçmişi</h2><button className="min-h-11 underline" onClick={onClose}>Kapat</button></div>{error?<p role="alert">{error}</p>:!data?<p role="status">Yükleniyor…</p>:<><ul className="space-y-3">{data.rows.map(e=><li key={e.commandId} className="rounded-lg border bg-white p-3"><p className="font-medium">{e.kind==='idp'?'İDP talebi açıldı':e.record?.cancelled?'Kadro iptal edildi':e.previous?'Kadro güncellendi':'Kadro oluşturuldu'}</p><p className="text-sm">{e.start} → {e.end??'Devam ediyor'} · {e.reason}</p>{e.previous&&<p className="text-xs text-slate-600">Önceki dönem: {e.previous.starts_on} → {e.previous.ends_on??'Devam ediyor'}</p>}<p className="text-xs text-slate-600">{new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(e.at))}</p>{e.periodId&&<Link className="inline-flex min-h-11 items-center underline" href={`/talepler/gunluk?firma=${row.company_id}&gun=${e.start}`}>İDP günlerini aç</Link>}</li>)}</ul><div className="flex gap-4"><button className="min-h-11 underline disabled:opacity-40" disabled={!offset} onClick={()=>setOffset(n=>n-50)}>Önceki</button><button className="min-h-11 underline disabled:opacity-40" disabled={!data.hasMore||offset>=100000} onClick={()=>setOffset(n=>n+50)}>Sonraki</button></div></>}</section>;
}
