'use client';
import {useEffect,useRef,useState} from 'react';
import {pilotDirectoryAction} from '../gunluk/actions';
import type {DirectoryPage} from '@/lib/operations/operations-directory';
export default function WorkerPicker({onSelect}:{onSelect:(id:string,name:string)=>void}){
 const [query,setQuery]=useState(''),[page,setPage]=useState<DirectoryPage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const seq=useRef(0);useEffect(()=>()=>{seq.current++;},[]);
 async function load(offset=0){const ticket=++seq.current;setBusy(true);setError('');setPage(null);try{const r=await pilotDirectoryAction({kind:'workers',companyId:null,search:query,status:'active',offset});if(ticket!==seq.current)return;if(r.ok)setPage(r.data);else setError(r.message);}catch{if(ticket===seq.current)setError('Personeller alınamadı. Tekrar arayın.');}finally{if(ticket===seq.current)setBusy(false);}}
 return <section className="space-y-3 rounded-xl border p-3"><label className="block text-sm">Sabit personel ara<input className="mt-1 min-h-11 w-full rounded-lg border p-3" value={query} maxLength={160} onChange={e=>{seq.current++;setBusy(false);setPage(null);setQuery(e.target.value);}}/></label><button type="button" disabled={busy} className="min-h-11 rounded-lg border px-4" onClick={()=>void load()}>Personelleri bul</button>{busy&&<p role="status">Aranıyor…</p>}{error&&<p role="alert">{error}</p>}{page&&<><ul>{page.rows.filter(r=>r.workerKind==='sabit').map(r=><li key={r.id}><button type="button" className="min-h-11 w-full border-b p-2 text-left hover:bg-slate-50" onClick={()=>onSelect(r.id,r.name)}>{r.name} · {r.code}</button></li>)}</ul>{!page.rows.some(r=>r.workerKind==='sabit')&&<p className="text-sm">Bu sayfada sabit personel yok. Aramayı daraltın veya sonraki sayfaya bakın. Kişi henüz operasyona hazır değilse personel havuzundan hazırlayın.</p>}<div className="flex gap-3"><button type="button" disabled={!page.offset||busy} onClick={()=>void load(page.offset-50)} className="min-h-11 underline disabled:opacity-40">Önceki</button><button type="button" disabled={page.offset+50>=page.total||busy} onClick={()=>void load(page.offset+50)} className="min-h-11 underline disabled:opacity-40">Sonraki</button></div></>}</section>;
}
