'use client';
import {useState} from 'react';
import {useAuth} from '@/context/AuthContext';
import {startTracking,type CheckOutcome,type ArrivalConfirmation} from '@/lib/operations/start-tracking';
const start=Date.parse('2026-09-09T08:00:00+03:00');
const outcomes:Record<CheckOutcome,string>={preparing:'Hazırlanıyor',on_way:'Yolda',claimed_arrival:'Şubede olduğunu söylüyor',unreachable:'Ulaşılamadı',cannot_attend:'Gelemeyecek'};
const statuses:Record<string,string>={removed:'Atama kaldırıldı',confirmed:'İşe başladı · teyitli',replacement_needed:'Yedek personel gerekli',arrival_unverified:'Başlangıç saati geldi · varış teyitsiz',unreachable:'Personele ulaşılamadı',check_overdue:'Kontrol gecikti',call_due:'Arama zamanı',planned:'Planlandı',arrival_pending:'Personel şubede olduğunu bildirdi · teyit bekleniyor'};
const time=(n:number)=>new Date(n).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'});
export default function Preview(){
 const {role,loading}=useAuth();const [minute,setMinute]=useState(-15),[calls,setCalls]=useState<Record<number,CheckOutcome>>({}),[selected,setSelected]=useState<number|null>(null),[confirmation,setConfirmation]=useState<ArrivalConfirmation>(),[witness,setWitness]=useState(''),[source,setSource]=useState<'branch'|'field'>('branch');
 if(loading)return <p>Yetki kontrol ediliyor…</p>;if(role!=='yonetici'&&role!=='operasyon')return <p>Bu önizleme yönetici ve operasyon ekibi içindir.</p>;
 const now=start+minute*60000,model=startTracking({startAt:start,now,checks:[-60,-30,-15].map(offsetMinutes=>({offsetMinutes,outcome:calls[offsetMinutes]})),confirmation});
 return <section className="max-w-4xl space-y-5"><h1 className="text-2xl font-semibold">İşe Başlama Takibi</h1>
 <p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm">Etkileşimli tasarım önizlemesi. Aşağıdaki personel ve şube örnektir; yaptığınız seçimler kaydedilmez, arama veya bildirim gönderilmez.</p>
 <div className="rounded border bg-white p-4 space-y-3"><label className="block text-sm">Senaryo saati: <strong>{time(now)}</strong><input aria-label="Senaryo saati" className="block w-full mt-3" type="range" min={-70} max={30} value={minute} onChange={e=>{setMinute(Number(e.target.value));setConfirmation(undefined);setCalls({});setSelected(null);}}/></label><p className="text-xs text-slate-500">Başlangıç 08.00. Önerilen kontroller: 07.00, 07.30, 07.45. Kaydırıcıyla zamanın etkisini deneyin.</p></div>
 <article className="rounded-xl border bg-white p-5 space-y-4"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">Örnek Personel · Merkez Şube</h2><p className="text-sm text-slate-600">İş başlangıcı 08.00 · Örnek takip sorumlusu: Operasyon ekibi</p></div><strong role="status" className={model.status==='confirmed'?'text-green-700':['planned','call_due'].includes(model.status)?'text-blue-700':'text-red-700'}>{statuses[model.status]}</strong></div>
 <div className="flex flex-wrap gap-2">{model.steps.map(s=><button key={s.offsetMinutes} disabled={Boolean(confirmation)||s.state==='upcoming'} onClick={()=>setSelected(s.offsetMinutes)} className={`rounded border px-3 py-2 text-sm ${s.state==='overdue'?'border-red-400 bg-red-50 text-red-800':s.state==='due'?'border-blue-400 bg-blue-50':s.state==='recorded'?'border-slate-400 bg-slate-100':'text-slate-500'}`}>{time(s.dueAt)} · {s.outcome?outcomes[s.outcome]:s.state==='not_required'?'Teyit nedeniyle gerekli değil':s.state==='upcoming'?'Planlı':s.state==='due'?'Şimdi ara':'Kontrol gecikti'}</button>)}</div>
 {selected!==null&&!confirmation&&<fieldset className="rounded border p-3"><legend>{time(start+selected*60000)} kontrol sonucu</legend><div className="flex flex-wrap gap-2">{Object.entries(outcomes).map(([value,label])=><button className="rounded border px-3 py-2 text-sm" key={value} onClick={()=>{setCalls(c=>({...c,[selected]:value as CheckOutcome}));setSelected(null);}}>{label}</button>)}</div></fieldset>}
 {!confirmation&&<fieldset className="border-t pt-4 space-y-3"><legend className="font-medium">İşe başladığını teyit et</legend><p className="text-sm text-slate-600">Personelin “şubedeyim” beyanı bu adımı tamamlamaz. Şube yetkilisinden veya saha sorumlusundan aldığınız teyidi kaydedin.</p><select aria-label="Teyit kaynağı" className="rounded border p-2" value={source} onChange={e=>setSource(e.target.value as 'branch'|'field')}><option value="branch">Şube yetkilisi</option><option value="field">Saha sorumlusu</option></select><input aria-label="Teyit eden kişi" className="rounded border p-2" placeholder="Teyit eden kişi" value={witness} onChange={e=>setWitness(e.target.value)}/><button disabled={!witness.trim()} className="rounded bg-green-700 px-3 py-2 text-white disabled:opacity-40" onClick={()=>setConfirmation({source,witness:witness.trim(),confirmedAt:now})}>Teyidi kaydet · Önizleme</button></fieldset>}
 {confirmation&&<p className="text-sm text-green-800">{time(confirmation.confirmedAt)} · {confirmation.witness} ({source==='branch'?'şube yetkilisi':'saha sorumlusu'}) teyit etti.</p>}
 <button className="text-sm underline" onClick={()=>{setCalls({});setConfirmation(undefined);setSelected(null);setWitness('');setMinute(-15);}}>Senaryoyu sıfırla</button></article>
 <p className="text-sm text-slate-600">Kırmızı kontrolün geciktiğini belirtir; personelin kesin gelmediği anlamına gelmez. Bu önizleme puantaj veya maaş hesabına veri yazmaz.</p></section>;
}
