'use client';
import {useEffect,useState} from 'react';import {Button} from '@/components/ui/button';import {useNavigationGuard} from '@/context/NavigationGuardContext';import type {TalentScope} from '@/lib/talent/people';import type {CallListEdit,CallListPeople} from '@/lib/talent/call-lists';import {talentCallListEditAction} from '../actions';
export default function CallListEditor({scope,list,onDirty,onSaved}:{scope:TalentScope;list:CallListPeople;onDirty:(v:boolean)=>void;onSaved:()=>void}){
 const [open,setOpen]=useState(false),[name,setName]=useState(list.name),[ids,setIds]=useState<string[]>([]),[pending,setPending]=useState<CallListEdit|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const guard=useNavigationGuard();
 useEffect(()=>{onDirty(open);return()=>onDirty(false);},[open,onDirty]);
 useEffect(()=>{if(!open)return;const off=guard.register(e=>{e.preventDefault();setMessage('Liste düzenlemesini tamamlayın veya kapatın.');});const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>{off();window.removeEventListener('beforeunload',stop);};},[open,guard]);
 async function save(operation:'rename'|'remove'){if(busy)return;const command=pending??{commandId:crypto.randomUUID(),id:list.id,revision:list.revision,operation,name:operation==='rename'?name:null,ids:operation==='remove'?ids:[]};setPending(command);setBusy(true);setMessage('');try{const r=await talentCallListEditAction(scope,command);if(!r.ok){setMessage(r.message);return;}setPending(null);setOpen(false);onSaved();}catch{setMessage('Sonuç alınamadı. Aynı işlemi yeniden deneyin.');}finally{setBusy(false);}}
 if(!list.canEdit)return null;
 return <section aria-label="Liste düzenleme" className={open?"mb-5 rounded-xl border border-slate-200 bg-slate-50 p-4":"mb-4 flex justify-end"}>{!open?<Button variant="outline" onClick={()=>{setName(list.name);setIds([]);setOpen(true);setMessage('');}}>Listeyi düzenle</Button>:<div className="space-y-3"><p className="text-sm">Kişiyi listeden çıkarmak havuz kaydını veya görüşmelerini silmez. Yeni kişiler havuzdaki seçim alanından eklenir.</p><fieldset disabled={busy||!!pending} className="space-y-3"><label className="block text-sm">Liste adı<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} className="block min-h-11 w-full rounded-lg border p-2"/></label><Button disabled={!name.trim()||name.trim()===list.name} onClick={()=>void save('rename')}>Adı kaydet</Button><ul className="max-h-72 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2">{list.people.map(p=><li key={p.id}><label className="flex min-h-11 items-center gap-3 rounded-lg px-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={ids.includes(p.id)} onChange={e=>setIds(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/>{p.name}</label></li>)}</ul><Button variant="outline" disabled={!ids.length||ids.length===list.people.length} onClick={()=>void save('remove')}>Seçilenleri listeden çıkar ({ids.length})</Button></fieldset>{pending&&<Button disabled={busy} onClick={()=>void save(pending.operation as 'rename'|'remove')}>Aynı işlemi yeniden dene</Button>}<Button variant="ghost" disabled={busy} onClick={()=>{setPending(null);setOpen(false);onSaved();}}>Kapat ve güncel listeyi getir</Button></div>}{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>;
}
