'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useAuth} from '@/context/AuthContext';
import {pilotCompaniesAction,pilotBoardAction,pilotScopeAction} from '../gunluk/actions';
import {schedulesAction,scheduleSaveAction,schedulePreviewAction,scheduleGenerateAction} from './actions';
import type {CommandScope} from '@/lib/operations/pending-commands';
import type {PilotCompany,PilotBoard} from '@/lib/operations/pilot-types';
import {validateScheduleSave,validateScheduleQuery,type Schedule,type ScheduleSave,type ScheduleQuery,type ScheduleWindow} from '@/lib/operations/recurring-schedules';
import {parseSchedulePending,type SchedulePending} from '@/lib/operations/schedule-pending';
import {addDays} from '@/lib/operations/weekly-plan';
import ScheduleEditor from './ScheduleEditor';
const button='min-h-11 rounded-lg border px-4 py-2 disabled:opacity-40';
const field='mt-1 block min-h-11 w-full rounded-lg border p-2';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul'}).format(new Date());
export default function Schedules(){
 const search=useSearchParams(),{user,role,loading}=useAuth();const [scope,setScope]=useState<CommandScope|null>(null),[companies,setCompanies]=useState<PilotCompany[]>([]),[company,setCompany]=useState(search.get('firma')??''),[error,setError]=useState('');
 useEffect(()=>{let current=true;if(loading||!user||!['yonetici','operasyon'].includes(role??''))return;Promise.all([pilotScopeAction(),pilotCompaniesAction()]).then(([s,c])=>{if(!current)return;if(!s.ok||!c.ok||s.data.actorId!==user.id)throw Error('Şirket erişimi alınamadı.');setScope(s.data);setCompanies(c.data);setCompany(old=>c.data.some(x=>x.id===old)?old:c.data[0]?.id??'');}).catch(()=>{if(current)setError('Firma ve yetkiler yüklenemedi. Sayfayı yenileyin.');});return()=>{current=false;};},[loading,user?.id,role]);
 if(loading)return <p role="status">Oturum yükleniyor…</p>;if(!['yonetici','operasyon'].includes(role??''))return <p>Plan yönetimine erişiminiz yok.</p>;
 return <section className="mx-auto max-w-5xl space-y-5"><header><h1 className="text-2xl font-semibold">Tekrarlayan planlar</h1><p className="mt-2 text-slate-600">Haftanın çalışma günlerini bir kez belirleyin. İhtiyacınız olan dönemi kontrol edip günlük plana ekleyin.</p></header>{error&&<p role="alert">{error}</p>}{scope&&company?<Content key={scope.tenantId+company} scope={scope} company={company} companies={companies} onCompany={setCompany}/>:<p role="status">{scope?'Önce operasyona açık bir firma ekleyin.':'Firmalar yükleniyor…'}</p>}</section>;
}
function Content({scope,company,companies,onCompany}:{scope:CommandScope;company:string;companies:PilotCompany[];onCompany:(v:string)=>void}){
 const [rows,setRows]=useState<Schedule[]|null>(null),[locations,setLocations]=useState<PilotBoard['locations']>([]),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [editor,setEditor]=useState<Schedule|null|undefined>(undefined),[selected,setSelected]=useState<Schedule|null>(null),[preview,setPreview]=useState<ScheduleWindow|null>(null),[query,setQuery]=useState<ScheduleQuery|null>(null);
 const [pending,setPending]=useState<SchedulePending|null>(null),[storageError,setStorageError]=useState(false);const sequence=useRef(0),working=useRef(false);
 const key=`bps:schedule:v1:${scope.actorId}:${scope.tenantId}:${company}`;
 const load=useCallback(async()=>{const ticket=++sequence.current;setBusy(true);setRows(null);setLocations([]);setError('');try{const [r,b]=await Promise.all([schedulesAction(scope,company,offset),pilotBoardAction(company,today())]);if(ticket!==sequence.current)return;if(!r.ok)throw Error(r.message);if(!b.ok)throw Error(b.message);setRows(r.data);setLocations(b.data.locations);}catch(e){if(ticket===sequence.current)setError(e instanceof Error?e.message:'Planlar yüklenemedi.');}finally{if(ticket===sequence.current)setBusy(false);}},[scope,company,offset]);
 useEffect(()=>{void load();return()=>{sequence.current++;};},[load]);
 useEffect(()=>{const read=()=>{try{const raw=localStorage.getItem(key);setPending(raw?parseSchedulePending(raw):null);setStorageError(false);}catch{setStorageError(true);setError('Bekleyen işlem okunamadı. Yeni işlem başlatılmadı; tarayıcı kaydını silmeden destek alın.');}};read();window.addEventListener('storage',read);return()=>window.removeEventListener('storage',read);},[key]);
 const blocked=busy||!!pending||storageError;
 async function execute(next:SchedulePending){
  if(working.current||storageError)return;working.current=true;setBusy(true);setError('');setNotice('');
  try{if(!navigator.locks)throw Error('Bu tarayıcı güvenli işlem kaydını desteklemiyor.');await navigator.locks.request(key,async()=>{
   const raw=localStorage.getItem(key),stored=raw?parseSchedulePending(raw):null;
   if(stored&&(stored.commandId!==next.commandId||stored.kind!==next.kind||JSON.stringify(stored.input)!==JSON.stringify(next.input))){setPending(stored);throw Error('Başka bir bekleyen işlem var. Önce onun sonucunu kontrol edin.');}
   localStorage.setItem(key,JSON.stringify(next));setPending(next);
   const r=next.kind==='save'?await scheduleSaveAction(scope,next.commandId,next.input):await scheduleGenerateAction(scope,next.commandId,next.input);
   if(!r.ok){if(r.rejected){localStorage.removeItem(key);setPending(null);}throw Error(r.message);}
   localStorage.removeItem(key);setPending(null);setEditor(undefined);setPreview(null);setSelected(null);setQuery(null);
   setNotice(next.kind==='save'?'Plan kaydedildi. Önceden açılan günlük işler değiştirilmedi.':`${'created'in r.data?r.data.created:0} yeni günlük talep oluşturuldu; ${'kept'in r.data?r.data.kept:0} mevcut kayıt korundu.`);
  });await load();}catch(e){setError(e instanceof Error?e.message:'Sonuç doğrulanamadı. Aynı işlemi yeniden kontrol edin.');}finally{working.current=false;setBusy(false);}
 }
 function save(value:ScheduleSave){try{void execute({kind:'save',commandId:crypto.randomUUID(),input:validateScheduleSave(value)});}catch(e){setError(e instanceof Error?e.message:'Plan geçersiz.');}}
 async function show(form:HTMLFormElement){if(!selected||blocked)return;setError('');setPreview(null);setQuery(null);setBusy(true);try{const f=new FormData(form),q=validateScheduleQuery({id:selected.id,revision:selected.revision,start:f.get('start'),end:f.get('end')});const r=await schedulePreviewAction(scope,q);if(!r.ok)throw Error(r.message);setPreview(r.data);setQuery(q);}catch(e){setError(e instanceof Error?e.message:'Önizleme alınamadı.');}finally{setBusy(false);}}
 return <><div className="flex flex-wrap items-end gap-3"><label className="min-w-48 flex-1 text-sm">Firma<select className={field} value={company} disabled={blocked||editor!==undefined||!!selected} onChange={e=>onCompany(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className={button} disabled={blocked||editor!==undefined} onClick={()=>{setSelected(null);setPreview(null);void load();}}>Listeyi yenile</button><Link className={button} href={`/talepler/gunluk?firma=${company}`}>Günlük plana dön</Link></div>
 {busy&&pending&&<p role="status" className="rounded-xl bg-blue-50 p-4">İşlem kaydediliyor…</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-900">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4">{notice}</p>}
 {pending&&!busy&&<aside className="rounded-xl border border-amber-300 p-4"><p>{pending.kind==='save'?'Plan kaydının':'Dönem oluşturma işleminin'} sonucu kontrol edilmeli. Yeniden kontrol etmek aynı işi iki kez oluşturmaz.</p><button className={button+' mt-3'} disabled={busy} onClick={()=>void execute(pending)}>Aynı işlemin sonucunu kontrol et</button></aside>}
 {editor!==undefined?<ScheduleEditor key={editor?.id??'new'} company={company} locations={locations} row={editor} disabled={blocked} onSave={save} onClose={()=>setEditor(undefined)}/>:<>
 <button className={button+' bg-blue-700 text-white'} disabled={blocked||!rows||!!selected||!locations.some(l=>l.active)} onClick={()=>{setNotice('');setEditor(null);}}>Yeni haftalık plan</button>
 {busy&&!rows?<p role="status">Planlar yükleniyor…</p>:rows&&<><div className="grid gap-3 md:grid-cols-2">{rows.slice(0,25).map(r=><article key={r.id} className="rounded-xl border bg-white p-4"><h2 className="font-semibold">{r.plan.title}{r.archived?' · Arşivde':''}</h2><p className="mt-1 text-sm">{locations.find(l=>l.id===r.plan.locationId)?.name??'Şube bilgisi yüklenemedi'} · {r.plan.position} · {r.plan.requiredCount} kişi</p><p className="mt-1 text-sm text-slate-600">{r.plan.weekdays.map(d=>['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][d-1]).join(' · ')}{r.plan.exceptions.length?` · ${r.plan.exceptions.length} istisna`: ''}</p><p className="mt-1 text-sm">{r.plan.clock.startTime}–{r.plan.clock.endTime}{r.plan.clock.nextDay?' (ertesi gün)':''} · {r.plan.start} → {r.plan.end}</p><div className="mt-3 flex flex-wrap gap-2"><button disabled={blocked||!!selected} className={button} onClick={()=>setEditor(r)}>Planı düzenle</button><button disabled={blocked||r.archived||!!selected} className={button+' bg-blue-50 text-blue-900'} onClick={()=>{setSelected(r);setPreview(null);setQuery(null);setError('');}}>Dönem oluştur</button></div></article>)}</div>{rows.length===0&&<p className="rounded-xl border p-5">Bu firmada kayıtlı plan yok. İlk planı oluşturarak çalışma günlerini ve saatlerini kaydedin.</p>}<div className="flex gap-3"><button className={button} disabled={blocked||!!selected||offset===0} onClick={()=>setOffset(n=>n-25)}>Önceki</button><button className={button} disabled={blocked||!!selected||rows.length<=25||offset>=100000} onClick={()=>setOffset(n=>n+25)}>Sonraki</button></div></>}
 </>}
 {selected&&<section className="space-y-4 rounded-xl border bg-white p-4" aria-label="Dönem oluştur"><h2 className="font-semibold">{selected.plan.title} · Dönem oluştur</h2><p className="text-sm text-slate-600">En fazla 31 gün seçin. Daha önce bu plandan açılmış işler, sonradan iptal edilmiş olsa da yeniden oluşturulmaz. Personel ataması günlük plandan yapılır.</p><form className="flex flex-wrap items-end gap-3" onChange={()=>{setPreview(null);setQuery(null);}} onSubmit={e=>{e.preventDefault();void show(e.currentTarget);}}><label>İlk gün<input disabled={blocked} className={field} type="date" name="start" min={selected.plan.start} max={selected.plan.end} defaultValue={selected.plan.start} required/></label><label>Son gün<input disabled={blocked} className={field} type="date" name="end" min={selected.plan.start} max={selected.plan.end} defaultValue={addDays(selected.plan.start,30)>selected.plan.end?selected.plan.end:addDays(selected.plan.start,30)} required/></label><button disabled={blocked} className={button}>Dönemi önizle</button><button type="button" disabled={busy} className={button} onClick={()=>{setSelected(null);setPreview(null);setQuery(null);}}>Kapat</button></form>
 {preview&&query&&<><p className="font-medium">{preview.rows.filter(r=>r.lifecycle==='new').length} yeni talep · {preview.rows.filter(r=>r.lifecycle!=='new').length} mevcut kayıt korunacak</p><ul className="max-h-96 space-y-2 overflow-y-auto">{preview.rows.map(r=><li key={r.workDate} className="flex flex-wrap justify-between gap-2 rounded-lg border p-3"><span>{r.workDate} · {r.clock.startTime}–{r.clock.endTime}{r.clock.nextDay?' (ertesi gün)':''} · {r.position} · {r.requiredCount} kişi</span>{r.requestId?<Link className="underline" href={`/talepler/gunluk?firma=${company}&gun=${r.workDate}&talep=${r.requestId}#talep-${r.requestId}`}>{r.lifecycle==='cancelled'?'İptal kayıt korunuyor':'Mevcut iş korunuyor'}</Link>:<strong className="text-blue-800">Yeni</strong>}</li>)}</ul>{!preview.rows.length&&<p>Bu aralıkta çalışma günü yok.</p>}<button className={button+' bg-blue-700 text-white'} disabled={blocked||!preview.rows.some(r=>r.lifecycle==='new')} onClick={()=>void execute({kind:'generate',commandId:crypto.randomUUID(),input:query})}>Yeni talepleri günlük plana ekle</button></>}
 </section>}</>;
}
