'use client';
import {useState} from 'react';
import type {PilotBoard} from '@/lib/operations/pilot-types';
import {validateScheduleSave,type Schedule,type ScheduleSave} from '@/lib/operations/recurring-schedules';
import {shiftDuration,type ShiftException} from '@/lib/operations/shift-window';
const field='mt-1 block min-h-11 w-full rounded-lg border p-2';const button='min-h-11 rounded-lg border px-4 py-2 disabled:opacity-40';
export default function ScheduleEditor({company,locations,row,disabled,onSave,onClose}:{company:string;locations:PilotBoard['locations'];row:Schedule|null;disabled:boolean;onSave:(p:ScheduleSave)=>void;onClose:()=>void}){
 const [exceptions,setExceptions]=useState<ShiftException[]>(row?.plan.exceptions??[]),[kind,setKind]=useState('off'),[error,setError]=useState('');
 function save(form:HTMLFormElement){setError('');try{const f=new FormData(form);onSave(validateScheduleSave({id:row?.id??null,revision:row?.revision??0,archived:f.get('archived')==='on',plan:{companyId:company,locationId:row?.plan.locationId??String(f.get('location')),title:f.get('title'),serviceLine:f.get('service'),position:f.get('position'),requiredCount:Number(f.get('count')),meetingNote:f.get('note'),start:f.get('start'),end:f.get('end'),weekdays:f.getAll('weekday').map(Number),clock:{startTime:f.get('clockStart'),endTime:f.get('clockEnd'),nextDay:f.get('nextDay')==='on'},exceptions}}));}catch(e){setError(e instanceof Error?e.message:'Plan geçersiz.');}}
 return <section className="space-y-4 rounded-xl border bg-white p-4" aria-label="Haftalık plan düzenle"><h2 className="text-lg font-semibold">{row?'Planı düzenle':'Yeni haftalık plan'}</h2><p className="text-sm text-slate-600">Bu şablon personel ihtiyacını üretir; çalışanı otomatik atamaz. Düzenleme ve arşivleme, önceden açılmış günlük talepleri değiştirmez.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3">{error}</p>}
 <form onSubmit={e=>{e.preventDefault();save(e.currentTarget);}}><fieldset disabled={disabled} className="grid gap-3 sm:grid-cols-2"><label>Plan adı<input className={field} name="title" maxLength={120} defaultValue={row?.plan.title} placeholder="Örn. Kadıköy sabah ekibi" required/></label><label>Şube<select className={field} name="location" disabled={!!row} defaultValue={row?.plan.locationId??''} required><option value="">Şube seçin</option>{locations.filter(l=>l.active||l.id===row?.plan.locationId).map(l=><option key={l.id} value={l.id}>{l.name}{!l.active?' (kapalı)':''}</option>)}</select></label><label>Hizmet<input className={field} name="service" defaultValue={row?.plan.serviceLine??'Temizlik'} maxLength={80} required/></label><label>Pozisyon<input className={field} name="position" defaultValue={row?.plan.position??'Temizlik görevlisi'} maxLength={80} required/></label><label>Vardiya başına kişi<input className={field} name="count" type="number" min={1} max={100} defaultValue={row?.plan.requiredCount??1} required/></label><label>Servis / buluşma notu<input className={field} name="note" maxLength={500} defaultValue={row?.plan.meetingNote??''}/></label><label>Geçerlilik başlangıcı<input className={field} type="date" name="start" min="2000-01-01" max="2100-12-31" defaultValue={row?.plan.start} required/></label><label>Geçerlilik bitişi<input className={field} type="date" name="end" min="2000-01-01" max="2100-12-31" defaultValue={row?.plan.end} required/></label><label>Başlangıç saati<input className={field} type="time" name="clockStart" defaultValue={row?.plan.clock.startTime??'08:00'} required/></label><label>Bitiş saati<input className={field} type="time" name="clockEnd" defaultValue={row?.plan.clock.endTime??'17:00'} required/></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="nextDay" defaultChecked={row?.plan.clock.nextDay}/>Bitiş ertesi gün</label><fieldset className="sm:col-span-2"><legend>Haftalık çalışma günleri</legend><div className="flex flex-wrap gap-3">{['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'].map((day,i)=><label className="flex min-h-11 items-center gap-2" key={day}><input type="checkbox" name="weekday" value={i+1} defaultChecked={(row?.plan.weekdays??[1,2,3,4,5]).includes(i+1)}/>{day}</label>)}</div></fieldset>{row&&<label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="archived" defaultChecked={row.archived}/>Planı arşivle (yeni dönem oluşturulmaz)</label>}<div className="flex gap-3 sm:col-span-2"><button className={button+' bg-blue-700 text-white'}>Planı kaydet</button><button className={button} type="button" onClick={onClose}>Vazgeç</button></div></fieldset></form>
 <details className="rounded-lg border p-3"><summary className="min-h-11 cursor-pointer py-2 font-medium">İstisna günleri · {exceptions.length} kayıt</summary><p className="my-2 text-sm text-slate-600">Tatil veya farklı saatli günleri ekleyin; resmî tatiller otomatik çıkarılmaz. Saat verirseniz haftalık planda olmayan güne de iş eklenir. En fazla 31 istisna kaydedilebilir. Değişiklikler yukarıdaki “Planı kaydet” ile saklanır.</p><form onSubmit={e=>{e.preventDefault();setError('');try{const f=new FormData(e.currentTarget),day=String(f.get('day'));if(!day||exceptions.some(x=>x.day===day)||exceptions.length>=31)throw Error('Farklı bir tarih seçin; en fazla 31 istisna eklenebilir.');const clock=kind==='off'?null:{startTime:String(f.get('start')),endTime:String(f.get('end')),nextDay:f.get('next')==='on'};if(clock)shiftDuration(clock);setExceptions(x=>[...x,{day,clock}].sort((a,b)=>a.day.localeCompare(b.day)));}catch(e){setError(e instanceof Error?e.message:'İstisna geçersiz.');}}}><fieldset disabled={disabled} className="grid gap-3 sm:grid-cols-2"><label>İstisna tarihi<input className={field} name="day" type="date" required/></label><label>Bu gün<select className={field} value={kind} onChange={e=>setKind(e.target.value)}><option value="off">Çalışma yok</option><option value="hours">Farklı saat / ek çalışma</option></select></label>{kind==='hours'&&<><label>İstisna başlangıç saati<input className={field} name="start" type="time" required/></label><label>İstisna bitiş saati<input className={field} name="end" type="time" required/></label><label className="flex min-h-11 items-center gap-2"><input name="next" type="checkbox"/>Ertesi gün biter</label></>}<button className={button}>İstisnayı listeye ekle</button></fieldset></form><ul className="mt-3 space-y-2">{exceptions.map(e=><li key={e.day} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-2"><span>{e.day} · {e.clock?`${e.clock.startTime}–${e.clock.endTime}${e.clock.nextDay?' (ertesi gün)':''}`:'Çalışma yok'}</span><button className={button} disabled={disabled} onClick={()=>setExceptions(x=>x.filter(v=>v.day!==e.day))}>Kaldır</button></li>)}</ul></details></section>;
}
