'use client';
import {useEffect,useRef,useState} from 'react';
import RightSidePanel from '@/components/ui/RightSidePanel';
import {Button} from '@/components/ui/button';
import {useNavigationGuard} from '@/context/NavigationGuardContext';
import type {CommandScope} from '@/lib/operations/pending-commands';
import {validateIdpInput,type IdpContext,type IdpInput} from '@/lib/operations/idp-context';
import {idpSaveAction} from './actions';
export type IdpTarget={requestId:string;day:string;label:string;initial:IdpContext|null};
export default function IdpContextPanel({scope,target,onClose,onSaved,onBusy}:{scope:CommandScope;target:IdpTarget;onClose:()=>void;onSaved:()=>void;onBusy:(v:boolean)=>void}){
 const [name,setName]=useState(target.initial?.original_name??''),[start,setStart]=useState(target.initial?.leave_start??target.day),[end,setEnd]=useState(target.initial?.leave_end??target.day),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<IdpInput|null>(null);
 const flight=useRef(false),guard=useNavigationGuard();
 useEffect(()=>{onBusy(true);const remove=guard.register(e=>{e.preventDefault();setMessage('Önce İDP panelini kaydedin veya kapatın.');});const block=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',block);return()=>{onBusy(false);remove();window.removeEventListener('beforeunload',block);};},[guard,onBusy]);
 async function save(form:HTMLFormElement){if(flight.current)return;let value:IdpInput;const data=new FormData(form);try{value=pending??validateIdpInput({commandId:crypto.randomUUID(),requestId:target.requestId,expectedRevision:target.initial?.revision??0,originalName:String(data.get("originalName")??""),leaveStart:String(data.get("leaveStart")??""),leaveEnd:String(data.get("leaveEnd")??"")});if(target.day<value.leaveStart||target.day>value.leaveEnd)throw Error();}catch{setMessage('Adı ve izin tarihlerini kontrol edin. Talep günü izin aralığında olmalı; dönem en fazla 367 takvim günü olabilir.');return;}
 flight.current=true;setBusy(true);setPending(value);setMessage('');try{const r=await idpSaveAction(scope,value);if(!r.ok){setMessage(r.message);return;}onSaved();}catch{setMessage('Yanıt alınamadı. Aynı işlemle yeniden deneyin.');}finally{flight.current=false;setBusy(false);}}
 const field='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white p-3 text-base';
 return <RightSidePanel open title="İzin yerine görevlendirme (İDP)" onClose={onClose} closeDisabled={busy}><p className="font-medium">{target.label} · {target.day}</p><p className="my-3 text-sm text-slate-600">İzinli asıl personeli belirtin. Yerine gelen kişi bu talebin normal atama alanından seçilir. Asıl personel için yeni havuz kaydı oluşturulmaz.</p><form onSubmit={e=>{e.preventDefault();void save(e.currentTarget);}} className="space-y-4"><fieldset disabled={busy||!!pending} className="space-y-4"><label className="block text-sm">İzne çıkan personel<input className={field} name="originalName" value={name} onChange={e=>setName(e.target.value)} maxLength={160} required autoComplete="off"/></label><label className="block text-sm">İzin başlangıcı<input className={field} type="date" min="2000-01-01" max="2100-12-31" name="leaveStart" value={start} onChange={e=>setStart(e.target.value)} required/></label><label className="block text-sm">İzin bitişi<input className={field} type="date" min={start} max="2100-12-31" name="leaveEnd" value={end} onChange={e=>setEnd(e.target.value)} required/></label></fieldset><p className="rounded-xl bg-blue-50 p-3 text-sm">Bu kayıt yalnız {target.day} tarihli talebi açıklar. İzin aralığındaki diğer günlere otomatik talep veya atama açılmaz.</p>{message&&<p role="status" className="text-sm text-amber-900">{message}</p>}<div className="grid grid-cols-2 gap-2"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Kapat</Button><Button type="submit" disabled={busy}>{busy?'Kaydediliyor…':pending?'Aynı işlemi dene':'Kaydet'}</Button></div>{pending&&<p className="text-xs text-slate-500">Kapatmak sunucudaki işlemi geri almaz. Yeniden düzenlemeden önce listeyi yenileyin.</p>}</form></RightSidePanel>;
}
