'use client';
import {useEffect,useState} from 'react';
import IdpPeriodHistory from './IdpPeriodHistory';
import IdpPeriodEditor from './IdpPeriodEditor';
import Link from 'next/link';
import RightSidePanel from '@/components/ui/RightSidePanel';
import type {CommandScope} from '@/lib/operations/pending-commands';
import type {IdpPeriodDay} from '@/lib/operations/idp-period';
import {idpPeriodReadAction} from './actions';
export default function IdpPeriodPanel({scope,periodId,onClose,onChanged}:{scope:CommandScope;periodId:string;onClose:()=>void;onChanged:()=>void}){
 const [mode,setMode]=useState<'update'|'cancel'|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [days,setDays]=useState<IdpPeriodDay[]|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let current=true;setDays(null);setError('');void idpPeriodReadAction(scope,periodId).then(r=>{if(!current)return;if(r.ok)setDays(r.data);else setError(r.message);}).catch(()=>{if(current)setError('Dönem yüklenemedi.');});return()=>{current=false;};},[scope,periodId,attempt]);
 return <RightSidePanel open title="İDP dönemi" onClose={onClose} closeDisabled={busy}>{error?<div role="alert">{error}<button className="ml-2 min-h-11 underline" onClick={()=>setAttempt(n=>n+1)}>Yeniden dene</button></div>:!days?<p role="status">Dönem yükleniyor…</p>:<><p className="font-semibold">{days[0].originalName} yerine</p><p className="my-2 text-sm">İzin: {days[0].leaveStart} – {days[0].leaveEnd}</p><p className="mb-4 text-sm text-slate-600">{days.length} çalışma günü · {days.filter(d=>d.lifecycle==='active'&&!d.assignedNames.length).length} gün personel bekliyor. Atama, işe gelindiği anlamına gelmez.</p>{notice&&<p role="status" className="my-3 text-sm text-green-700">{notice}</p>}{days[0].periodCancelled?<p className="my-3 rounded-xl bg-slate-100 p-3">Bu dönem iptal edildi. Geçmiş kayıtlar korunuyor.</p>:mode?<IdpPeriodEditor key={`${periodId}:${days[0].periodRevision}:${mode}`} scope={scope} periodId={periodId} days={days} mode={mode} onBusy={setBusy} onCancel={()=>{setMode(null);setAttempt(n=>n+1);onChanged();}} onDone={()=>{setMode(null);setNotice('Dönem güncellendi.');setAttempt(n=>n+1);onChanged();}}/>:<div className="mb-4 flex flex-wrap gap-2"><button type="button" className="min-h-11 rounded-xl border px-3 text-sm" onClick={()=>setMode('update')}>Düzelt / gün ekle</button><button type="button" className="min-h-11 rounded-xl border px-3 text-sm text-red-700" onClick={()=>setMode('cancel')}>Dönemi iptal et</button></div>}<ul className="space-y-3">{days.map(d=><li key={d.requestId} className="rounded-xl border p-3"><p className="font-medium">{d.day} {d.lifecycle==='cancelled'&&'· İptal edildi'}</p><p className="my-1 text-sm">{d.assignedNames.length?d.assignedNames.join(', '):d.lifecycle==='cancelled'?'Atama yok':'Henüz personel atanmadı'}</p><Link aria-disabled={!!mode} onClick={e=>{if(mode){e.preventDefault();return;}onClose();}} className="inline-flex min-h-11 items-center text-sm text-blue-700 underline" href={`/talepler/gunluk?firma=${d.companyId}&gun=${d.day}#talep-${d.requestId}`}>Günün talebine git</Link></li>)}</ul><IdpPeriodHistory key={`${periodId}:${days[0].periodRevision}`} scope={scope} periodId={periodId} revision={days[0].periodRevision}/></>}</RightSidePanel>;
}
