import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const js=ts.transpileModule(readFileSync(new URL('../src/lib/supabase/companies.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {selectCompaniesByIds,selectCompaniesByLegacyMockIds,selectAllCompanies}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const row=i=>({id:'00000000-0000-4000-8000-'+String(i).padStart(12,'0'),name:'Company '+i,legacy_mock_id:'legacy-'+i});
function client(load){const calls=[];return {calls,from:()=>{let column,keys,cursor;const q={select:()=>q,in:(c,k)=>(column=c,keys=[...k],q),order:()=>q,limit:()=>q,gt:(_c,id)=>(cursor=id,q),then:(resolve,reject)=>{const call={column,keys,cursor};calls.push(call);return Promise.resolve(load({...call,index:calls.length})).then(resolve,reject);}};return q;}};}
const visible=(rows,{column,keys,cursor},cap=100)=>({data:rows.filter(r=>keys.includes(r[column])&&(!cursor||r.id>cursor)).slice(0,cap),error:null});
test('large UUID set is split, deduped, scoped and complete',async()=>{const rows=Array.from({length:200},(_,i)=>row(i+1)),ids=rows.map(r=>r.id);const c=client(p=>visible(rows,p));const result=await selectCompaniesByIds(c,[...ids,ids[0],row(999).id]);assert.equal(result.length,200);assert.ok(c.calls.filter(p=>!p.cursor).length>1);assert.ok(c.calls.every(p=>p.column==='id'&&p.keys.length<=75));assert.equal(new Set(result.map(r=>r.id)).size,200);});
test('short server pages and invisible keys do not truncate legacy results',async()=>{const rows=[row(1),row(2),row(3)];const c=client(p=>visible(rows,p,1));assert.equal((await selectCompaniesByLegacyMockIds(c,['legacy-1','legacy-2','legacy-3','missing'])).length,3);assert.equal(c.calls.length,4);});
test('encoded Unicode legacy keys also produce bounded filters',async()=>{const rows=Array.from({length:20},(_,i)=>({...row(i+1),legacy_mock_id:'Şube'.repeat(25)+i}));const c=client(p=>visible(rows,p));assert.equal((await selectCompaniesByLegacyMockIds(c,rows.map(r=>r.legacy_mock_id))).length,20);assert.ok(c.calls.filter(p=>!p.cursor).length>=2);assert.ok(c.calls.every(p=>new URLSearchParams({legacy_mock_id:'in.('+p.keys.join(',')+')'}).toString().length<3100));});
test('later batch failure rejects instead of returning partial rows',async()=>{const rows=Array.from({length:100},(_,i)=>row(i+1));const c=client(p=>p.index===3?{data:null,error:{message:'private detail'}}:visible(rows,p));await assert.rejects(selectCompaniesByIds(c,rows.map(r=>r.id)),/page failed/);});
test('empty, invalid and oversized keys never issue an unscoped query',async()=>{const c=client(()=>{throw Error('unexpected query');});assert.deepEqual(await selectCompaniesByIds(c,[]),[]);for(const keys of [undefined,null,[''],[undefined]])await assert.rejects(selectCompaniesByIds(c,keys),/invalid keys/);await assert.rejects(selectCompaniesByLegacyMockIds(c,['Ş'.repeat(1000)]),/key too long/);assert.equal(c.calls.length,0);});
test('null success, wrong-scope rows and repeated cursors fail closed',async()=>{await assert.rejects(selectCompaniesByIds(client(()=>({data:null,error:null})),[row(1).id]),/invalid page/);await assert.rejects(selectCompaniesByIds(client(()=>({data:[row(2)],error:null})),[row(1).id]),/scope mismatch/);await assert.rejects(selectCompaniesByIds(client(()=>({data:[row(1)],error:null})),[row(1).id]),/did not advance/);});

test('directory continues past short pages to include every visible company',async()=>{const rows=[row(1),row(2),row(3),row(4),row(5)];const c=client(({cursor})=>({data:rows.filter(r=>!cursor||r.id>cursor).slice(0,2),error:null}));assert.deepEqual(await selectAllCompanies(c),rows);assert.equal(c.calls.length,4);assert.ok(c.calls.every(p=>p.keys===undefined));});
test('directory page error/null/non-progress fail without partial success',async()=>{await assert.rejects(selectAllCompanies(client(({index})=>index===1?{data:[row(1)],error:null}:{data:null,error:{message:'private'}})),/page failed/);await assert.rejects(selectAllCompanies(client(()=>({data:null,error:null}))),/invalid page/);await assert.rejects(selectAllCompanies(client(()=>({data:[row(1)],error:null}))),/did not advance/);});
test('directory empty and bounded growth terminate explicitly',async()=>{assert.deepEqual(await selectAllCompanies(client(()=>({data:[],error:null}))),[]);const c=client(({index})=>({data:[row(index)],error:null}));await assert.rejects(selectAllCompanies(c),/scan limit exceeded/);assert.equal(c.calls.length,201);});
