import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=readFileSync(new URL('../src/lib/supabase/documents.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {selectAllDocuments}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const row=(i,date='2026-09-01')=>({id:'00000000-0000-4000-8000-'+String(i).padStart(12,'0'),updated_at:date});
function client(load){let calls=0;return {from:()=>{let cursor=null,limit;const q={select:()=>q,order:()=>q,limit:n=>(limit=n,q),gt:(_key,id)=>(cursor=id,q),then:(resolve,reject)=>Promise.resolve(load({cursor,limit,call:++calls})).then(resolve,reject)};return q;},get calls(){return calls;}};}
test('reads past short capped pages until empty and returns newest first with deterministic ties',async()=>{const rows=[row(1,'2020-01-01'),row(2),row(3),row(4,'2027-01-01'),row(5)];const c=client(({cursor,limit})=>({data:rows.filter(r=>!cursor||r.id>cursor).slice(0,Math.min(limit,2)),error:null}));assert.deepEqual((await selectAllDocuments(c)).map(r=>r.id),[4,2,3,5,1].map(i=>row(i).id));assert.equal(c.calls,4);});
test('empty visible dataset is a complete empty result',async()=>assert.deepEqual(await selectAllDocuments(client(()=>({data:[],error:null}))),[]));
test('a later-page error rejects instead of exposing the first page',async()=>{const c=client(({call})=>call===1?{data:[row(1)],error:null}:{data:null,error:{message:'private backend detail'}});await assert.rejects(selectAllDocuments(c),/page failed/);assert.equal(c.calls,2);});
test('null success, repeated cursor and unordered pages fail closed',async()=>{await assert.rejects(selectAllDocuments(client(()=>({data:null,error:null}))),/invalid page/);await assert.rejects(selectAllDocuments(client(()=>({data:[row(1)],error:null}))),/did not advance/);await assert.rejects(selectAllDocuments(client(()=>({data:[row(2),row(1)],error:null}))),/did not advance/);});
test('bounded scan rejects continuous growth instead of returning partial rows',async()=>{const c=client(({call})=>({data:[row(call)],error:null}));await assert.rejects(selectAllDocuments(c),/scan limit exceeded/);assert.equal(c.calls,201);});
