import test from 'node:test';import assert from 'node:assert/strict';import {importActualTypeScript} from './helpers/import-typescript.mjs';
const {reserveMizan,settleMizan}=await importActualTypeScript(new URL('../src/lib/luca/pending-import.ts',import.meta.url));
const scope={actorId:'00000000-0000-4000-8000-000000000001',tenantId:'00000000-0000-4000-8000-000000000002'},file='a'.repeat(64);
function fixture(){const disk=new Map(),queues=new Map();return {disk,storage:{getItem:k=>disk.get(k)??null,setItem:(k,v)=>disk.set(k,v),removeItem:k=>disk.delete(k)},locks:{request(k,fn){const r=(queues.get(k)??Promise.resolve()).then(fn);queues.set(k,r.catch(()=>{}));return r;}}};}
test('reload and concurrent tabs reuse identity without retaining financial text',async()=>{const f=fixture(),payload={salary:'Synthetic private payroll',amount:123};const ids=await Promise.all(Array.from({length:10},()=>reserveMizan(scope,file,payload,{...f.storage},f.locks)));assert.equal(new Set(ids).size,1);assert.equal(await reserveMizan(scope,file,{amount:123,salary:payload.salary},f.storage,f.locks),ids[0]);assert.ok(!JSON.stringify([...f.disk]).includes('Synthetic'));assert.ok(!JSON.stringify([...f.disk]).includes('salary'));});
test('changed file or mapping cannot silently allocate a second command',async()=>{const f=fixture();await reserveMizan(scope,file,{company:'a'},f.storage,f.locks);await assert.rejects(()=>reserveMizan(scope,'b'.repeat(64),{company:'a'},f.storage,f.locks));await assert.rejects(()=>reserveMizan(scope,file,{company:'b'},f.storage,f.locks));assert.equal(f.disk.size,1);});
test('scope isolation; settlement clears only the proven command',async()=>{const f=fixture(),id=await reserveMizan(scope,file,{},f.storage,f.locks);await settleMizan(scope,scope.actorId,f.storage,f.locks);assert.equal(await reserveMizan(scope,file,{},f.storage,f.locks),id);assert.notEqual(await reserveMizan({...scope,tenantId:scope.actorId},file,{},f.storage,f.locks),id);await settleMizan(scope,id,f.storage,f.locks);assert.notEqual(await reserveMizan(scope,file,{},f.storage,f.locks),id);});
test('storage failure and corrupt records fail closed',async()=>{const f=fixture();await assert.rejects(()=>reserveMizan(scope,file,{}, {...f.storage,setItem(){throw Error('quota');}},f.locks));await assert.rejects(()=>reserveMizan(scope,file,{},f.storage,undefined));await reserveMizan(scope,file,{},f.storage,f.locks);f.disk.set([...f.disk.keys()][0],'{');await assert.rejects(()=>reserveMizan(scope,file,{},f.storage,f.locks));});
test('failed settlement retains original identity',async()=>{const f=fixture(),id=await reserveMizan(scope,file,{},f.storage,f.locks);await assert.rejects(()=>settleMizan(scope,id,{...f.storage,removeItem(){throw Error('blocked');}},f.locks));assert.equal(await reserveMizan(scope,file,{},f.storage,f.locks),id);});

test('only explicit input rejection permits clearing recovery; network/replay uncertainty preserves it',async()=>{const {isRejectedMizanInput}=await importActualTypeScript(new URL('../src/lib/luca/pending-import.ts',import.meta.url));assert.equal(isRejectedMizanInput({code:'P0001',message:'MIZAN_INPUT'}),true);for(const e of [{message:'MIZAN_INPUT'},{code:'P0001',message:'MIZAN_REPLAY_MISMATCH'},{code:'503',message:'timeout'},{code:'P0001',message:'MIZAN_SCOPE'}])assert.equal(isRejectedMizanInput(e),false);});
