import test from 'node:test';import assert from 'node:assert/strict';import {importActualTypeScript} from './helpers/import-typescript.mjs';
const {startTracking}=await importActualTypeScript(new URL('../src/lib/operations/start-tracking.ts',import.meta.url));
const startAt=Date.parse('2026-09-09T08:00:00+03:00'),checks=[-60,-30,-15].map(offsetMinutes=>({offsetMinutes}));const run=(minute,extra={})=>startTracking({startAt,now:startAt+minute*60000,checks,...extra});
test('future, due and overdue controls have distinct boundaries',()=>{assert.equal(run(-61).status,'planned');assert.equal(run(-60).status,'call_due');assert.equal(run(-55).status,'check_overdue');});
test('claimed arrival never confirms; start deadline escalates even after all calls',()=>{const done=checks.map(c=>({...c,outcome:'claimed_arrival'}));assert.equal(run(-1,{checks:done}).status,'arrival_pending');assert.equal(run(0,{checks:done}).status,'arrival_unverified');});
test('cannot attend needs replacement; unreachable differs from absence',()=>{assert.equal(run(-14,{checks:[{offsetMinutes:-15,outcome:'cannot_attend'}]}).status,'replacement_needed');assert.equal(run(-14,{checks:[{offsetMinutes:-15,outcome:'unreachable'}]}).status,'unreachable');});
test('verified arrival skips remaining controls, retains recorded outcomes',()=>{const r=run(-20,{checks:[{offsetMinutes:-60,outcome:'on_way'},...checks.slice(1)],confirmation:{source:'branch',witness:'Test manager',confirmedAt:startAt-20*60000}});assert.equal(r.status,'confirmed');assert.equal(r.steps[0].state,'recorded');assert.equal(r.steps[2].state,'not_required');assert.equal(r.next,null);});
test('removed assignment closes pending controls; invalid confirmation cannot green a row',()=>{assert.equal(run(1,{removed:true}).status,'removed');for(const confirmation of [{source:'worker',witness:'A',confirmedAt:startAt},{source:'branch',witness:'',confirmedAt:startAt},{source:'branch',witness:'A',confirmedAt:startAt+60000}])assert.throws(()=>run(0,{confirmation}));});
test('midnight arithmetic and malformed schedules',()=>{const t=Date.parse('2026-09-10T00:15:00+03:00');assert.equal(new Date(startTracking({startAt:t,now:t,checks}).steps[0].dueAt).toISOString(),'2026-09-09T20:15:00.000Z');assert.throws(()=>run(0,{checks:[checks[0],checks[0]]}));});
