import {test} from 'node:test';
import assert from 'node:assert/strict';
import {importActualTypeScript} from './helpers/import-typescript.mjs';
const {weekStart,addDays,parseWeeklyPlan,weeklyTotals,weeklyCsv}=await importActualTypeScript(new URL('../src/lib/operations/weekly-plan.ts',import.meta.url));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const row=(n,date='2026-12-28')=>({id:id(n),locationId:id(2),locationName:'Merkez',city:'İstanbul',workDate:date,serviceLine:'Temizlik',position:'Görevli',requiredCount:2,lifecycle:'active',assignments:[]});
const fixture=()=>({companyId:id(1),companyName:'Test firma',weekStart:'2026-12-28',generatedAt:'2026-12-28T10:00:00+00:00',requests:[row(3)]});
test('Monday week boundaries include Sunday, leap day, year and minimum date',()=>{assert.equal(weekStart('2027-01-03'),'2026-12-28');assert.equal(weekStart('2027-01-04'),'2027-01-04');assert.equal(weekStart('2024-02-29'),'2024-02-26');assert.equal(weekStart('2000-01-01'),'1999-12-27');assert.equal(addDays('2024-02-28',1),'2024-02-29');assert.throws(()=>weekStart('2026-02-30'));assert.throws(()=>weekStart('2101-01-01'));});
test('totals count person-days, exclude cancellations and retain unfilled requests',()=>{const a=row(3),b=row(4,'2026-12-29'),c={...row(5),lifecycle:'cancelled'};a.assignments=[{id:id(10),workerId:id(20),name:'A'}];b.assignments=[{id:id(11),workerId:id(20),name:'A'}];assert.deepEqual(weeklyTotals([a,b,c]),{requests:2,cancelled:1,required:4,assigned:2,open:2});assert.deepEqual(weeklyTotals([]),{requests:0,cancelled:0,required:0,assigned:0,open:0});});
test('empty verified plan is accepted; null and wrong company/week are not',()=>{const p=fixture();p.requests=[];assert.deepEqual(parseWeeklyPlan(p,id(1),p.weekStart),p);assert.throws(()=>parseWeeklyPlan(null,id(1),p.weekStart));assert.throws(()=>parseWeeklyPlan(p,id(2),p.weekStart));assert.throws(()=>parseWeeklyPlan(p,id(1),'2027-01-04'));});
test('range, duplicate requests, capacity, missing staff and cancelled assignment contradictions fail closed',()=>{
 const cases=[p=>{p.requests[0].workDate='2027-01-04';},p=>{p.requests.push(p.requests[0]);},p=>{p.requests[0].requiredCount=0;},p=>{p.requests[0].assignments=[{id:id(4),workerId:id(5)}];},p=>{p.requests[0].lifecycle='cancelled';p.requests[0].assignments=[{id:id(4),workerId:id(5),name:'A'}];}];
 for(const change of cases){const p=fixture();change(p);assert.throws(()=>parseWeeklyPlan(p,id(1),p.weekStart));}
});
test('same worker on separate days allowed, double booking or repeated assignment ID rejected',()=>{const p=fixture();p.requests[0].assignments=[{id:id(10),workerId:id(20),name:'A'}];p.requests.push({...row(4,'2026-12-29'),assignments:[{id:id(11),workerId:id(20),name:'A'}]});parseWeeklyPlan(p,id(1),p.weekStart);p.requests[1].workDate='2026-12-28';assert.throws(()=>parseWeeklyPlan(p,id(1),p.weekStart));p.requests[1].workDate='2026-12-29';p.requests[1].assignments[0].id=id(10);assert.throws(()=>parseWeeklyPlan(p,id(1),p.weekStart));});
test('CSV records scope/time and quotes delimiters, double quotes and embedded newlines',()=>{const p=fixture();p.companyName='Test; "A"\nB';const csv=weeklyCsv(p,false);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('"Test; ""A""\nB"'));assert.ok(csv.includes('"2026-12-28T10:00:00+00:00"'));assert.ok(csv.includes('"Aktif talepler"'));assert.ok(csv.endsWith('\r\n'));});
test('CSV neutralizes formula prefixes including whitespace before formula',()=>{for(const value of ['=1+1','+SUM(A1)','-1+2','@SUM(A1)','\t=1+1','\r\n=1']){const p=fixture();p.requests[0].locationName=value;assert.ok(weeklyCsv(p,false).includes('"\''+value+'"'));}});
test('CSV cancellations are opt-in and contribute zero active open',()=>{const p=fixture();p.requests[0].lifecycle='cancelled';assert.equal(weeklyCsv(p,false).split('\r\n').length,2);const csv=weeklyCsv(p,true);assert.ok(csv.includes('"İptaller dahil"'));assert.ok(csv.includes('"İptal";"2";"0";"0"'));});
