import type {SupabaseClient} from '@supabase/supabase-js';
import type {Database} from '@/types/database.types';
import type {CommandScope} from '@/lib/operations/pending-commands';
import {isUuid} from '@/lib/operations/pilot-validation';
import {validateScheduleSave,validateScheduleQuery,parseScheduleList,parseScheduleWindow,parseScheduleSaveReceipt,parseScheduleGeneration} from '@/lib/operations/recurring-schedules';
function scope(s:CommandScope){if(!s||!isUuid(s.actorId)||!isUuid(s.tenantId))throw Error('OPS_SCOPE_CHANGED');return {p_actor:s.actorId,p_tenant:s.tenantId};}
export async function listSchedules(c:SupabaseClient<Database>,s:CommandScope,company:string,offset:number){if(!isUuid(company)||!Number.isInteger(offset)||offset<0||offset>100000)throw Error('SCHEDULE_INPUT');const r=await c.rpc('ops_schedule_list',{...scope(s),p_company:company,p_offset:offset}).abortSignal(AbortSignal.timeout(12000));if(r.error)throw r.error;return parseScheduleList(r.data,s.tenantId,company,offset);}
export async function saveSchedule(c:SupabaseClient<Database>,s:CommandScope,id:string,input:unknown){if(!isUuid(id))throw Error('SCHEDULE_INPUT');const p=validateScheduleSave(input);const r=await c.rpc('ops_schedule_save',{...scope(s),p_command:id,p_id:p.id,p_revision:p.revision,p_plan:p.plan,p_archived:p.archived}).abortSignal(AbortSignal.timeout(12000));if(r.error)throw r.error;return parseScheduleSaveReceipt(r.data,s.tenantId,id,p);}
export async function previewSchedule(c:SupabaseClient<Database>,s:CommandScope,input:unknown){const p=validateScheduleQuery(input);const r=await c.rpc('ops_schedule_preview',{...scope(s),p_id:p.id,p_revision:p.revision,p_start:p.start,p_end:p.end}).abortSignal(AbortSignal.timeout(12000));if(r.error)throw r.error;return parseScheduleWindow(r.data,s.tenantId,p);}
export async function generateSchedule(c:SupabaseClient<Database>,s:CommandScope,id:string,input:unknown){if(!isUuid(id))throw Error('SCHEDULE_INPUT');const p=validateScheduleQuery(input);const r=await c.rpc('ops_schedule_generate',{...scope(s),p_command:id,p_id:p.id,p_revision:p.revision,p_start:p.start,p_end:p.end}).abortSignal(AbortSignal.timeout(12000));if(r.error)throw r.error;return parseScheduleGeneration(r.data,s.tenantId,id,p);}
