-- ==========================================================================
-- BPS — Close the complete_appointment_atomic RPC exposure
-- ==========================================================================
-- `complete_appointment_atomic(uuid, text, text, boolean)` was created
-- (20260407001700) as SECURITY DEFINER with NO explicit GRANT/REVOKE, so
-- its EXECUTE privilege followed the PostgreSQL default (granted to PUBLIC).
-- Because it is SECURITY DEFINER it runs as the owner and BYPASSES RLS, and
-- it performs NO role/scope check on p_appointment_id. Net effect: any
-- authenticated user could call it via PostgREST to complete ANY appointment
-- and insert a task into ANY company — a privilege escalation / data-integrity
-- hole.
--
-- The RPC is UNUSED by the app: the live path is the service-layer
-- `completeAppointment` (src/lib/services/appointments.ts), which is now
-- hardened (passive-company guard on the task side-effect + idempotency,
-- commit 9370032). So the safe, minimal closure is to revoke EXECUTE.
-- NOTE (corrected 2026-07-29, after applying): an earlier draft of this note
-- claimed the RPC had no explicit grants, and therefore that revoking from
-- PUBLIC would strip EXECUTE from every role including service_role. Measured
-- in prod, that is wrong on both counts: `service_role` and `postgres` hold
-- DIRECT EXECUTE grants, which a `REVOKE ... FROM PUBLIC, anon, authenticated`
-- does not touch — and should not. service_role is not rolsuper and inherits
-- from no other role, so its access comes from that direct grant alone.
-- Post-apply measurement: anon = false, authenticated = false,
-- service_role = TRUE. That is exactly the intended end state — outside roles
-- shut, server side open — so the "grant EXECUTE to service_role later if a
-- caller appears" step the earlier note described is unnecessary; the grant is
-- already there.
--
-- ✅ APPLIED 2026-07-29 (prod, SQL Editor) and recorded in the migration
--    ledger by an explicit-version `migration repair --status applied`.
--    Pre-apply grants were PUBLIC, anon, authenticated, postgres, service_role.
--    Note for other environments: anon and authenticated were EXPLICIT
--    grantees, not merely PUBLIC inheritors — Supabase issues a default
--    GRANT EXECUTE on public-schema functions to both. Revoking only FROM
--    PUBLIC would therefore have left them able to call it. This statement
--    names all three deliberately. Verify with has_function_privilege(), not
--    the grant listing, since it answers explicit and inherited together:
--        select has_function_privilege('anon',
--          'public.complete_appointment_atomic(uuid, text, text, boolean)',
--          'EXECUTE');
--
-- ⚠ RE-ENABLING LATER: if the team decides to adopt this atomic RPC (it has
--    row-lock + idempotency the service layer implements in app code), do
--    NOT simply re-grant. First add an in-function role/scope gate mirroring
--    the service layer (yonetici global + partner within
--    partner_company_assignments; block goruntuleyici/muhasebe) and a
--    passive-company check on the task insert, THEN grant EXECUTE.
-- ==========================================================================

REVOKE EXECUTE ON FUNCTION
  public.complete_appointment_atomic(uuid, text, text, boolean)
  FROM PUBLIC, anon, authenticated;
